services:
  backend:
    image: backend
    build:
      context: ./requirements/backend
    container_name: backend
    volumes:
      - ./requirements/backend/app:/app
    ports:
      - 3000:3000
    restart: always
    networks:
      - network

  frontend:
    image: frontend
    build:
      context: ./requirements/frontend
    container_name: frontend
    volumes:
      - ./requirements/frontend/app:/app
      - /app/node_modules
      - /app/dist
      - frontend_volume:/var/www/html
    ports:
      - 4443:443
    restart: always
    networks:
      - network

volumes:
  frontend_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/tmp/data/frontend'

networks:
  network:
    driver: bridge
